### PR TITLE
Added important bug fix

### PR DESCRIPTION
**Pull request by micahdbak**
This is a serious bug I just discovered. Please merge my PR to fix it. Thanks.

### CODE REVIEW

**Comment by micahdbak** [comment]
merge i

**Comment by micahdbak** [comment]
merge it

**Comment by micahdbak** [comment]
!!!!! merge it !!!!!!

**Comment by nilocnus** [comment]
Omg is that the real Micah baker??!

**Comment by micahdbak** [comment]
IT IS! now merge my PR, please

**Pull request merged**
